### ISSUE TITLE
wallaby fails to load

### ISSUE THREAD

**Issue by igoldny** [Drathal/angular-webpack-dashboard#2]
there is two seperat issues related to wallaby
1. i get this error some thing related to chai 
   RangeError: Maximum call stack size exceeded.
   at node_modules/karma-sinon-chai/node_modules/chai/chai.js:3524
2. wallaby cant find those files:
   -require('../../../node_modules/angular-material/angular-material.scss');
   -require('../../../node_modules/angular-loading-bar/build/loading-bar.css');
   -require('../../../node_modules/material-design-icons-iconfont/dist/material-design-icons.scss');
   -require('../../../node_modules/angular-chart.js/dist/angular-chart.css');

**Comment by Drathal** [comment]
I had a look into it but get stuck using the wallaby-webpack plugin. I opened a issue here: https://github.com/jeffling/wallaby-webpack/issues/15#issuecomment-143156261

**Comment by Drathal** [comment]
fixed.  commit: https://github.com/Drathal/angular-webpack-dashboard/commit/ca5393708ca6c74afe4de5ae8be119986993c8aa
